### ISSUE TITLE
Resource not found.. was working

### ISSUE THREAD

**Issue by zefie** [xdarklight/cm-update-server#10]
This is probably user error, and I apologize in advance, but I had this working quite well with lineageos 13.0, but I am building bleeding edge nightlys and today I noticed the update interface changed in the ROM, and it is now sending a request for (cm.updater.uri)/v1/gtelwifiue/nightly/86b81c2c73 .. (gtelwifiue being the device) the numbers at the end being the romID I assume. But the cm-update-server is returning resource not found. It works with a previous build before the UI change. I looked through LineageOS commits for the updater app but maybe thats the wrong place because I didnt see any changes.

In any case the issue is that this server no longer seems to work with the "new" updater they made, because as I said, I had it set up and working with previous builds. This is what the new UI looks like:

![capture](https://cloud.githubusercontent.com/assets/612177/24310370/13fda108-10a6-11e7-9c27-b32558cba310.PNG)

**Comment by xdarklight** [comment]
this doesn't sound like a user error!

I'll try to look into this once I have time:
we probably have to move some of the functionality into separate functions.
after that we can introduce new endpoints (like /api/v1/device/type/incremental) which simply use the same internal logic as the old endpoints (this will make cm-update-server compatible with both, CMUpdater and LineageOS Updater).

if I start with such changes: will you be able to test this with an actual LineageOS device?

**Comment by zefie** [comment]
I can, and am willing to test with my builds of LineageOS 13.0 for my tablet. I don't have any "officially supported" LineageOS devices, if that is what you mean though.

The screenshot is from my tablet, but from software casting to my PC. I may have been too tired, or they may have removed the "Screenshot from power menu" option, because I could not find it!

**Comment by xdarklight** [comment]
I didn't mean officially supported devices (as these get updates through the official server).

I will keep you updated once I found time to look into this.

**Comment by xdarklight** [comment]
I am not maintaining this project anymore so I'm closing this.
