### ISSUE TITLE
Adding support for LineageOS new's API

### ISSUE THREAD

**Issue by Cubox** [xdarklight/cm-update-server#13]
Hi,

I wish to continue to use your software, however since LineageOS changed the API I only get 404s.
The exact place where the URLs are generated is https://github.com/LineageOS/android_packages_apps_CMUpdater/blob/cm-14.1/src/com/cyanogenmod/updater/service/UpdateCheckService.java#L223

Thanks :)

**Comment by xdarklight** [comment]
I am not maintaining this project anymore so I'm closing this.
