### ISSUE TITLE
Error when hitting /api with simple POST after first ROM addition

### ISSUE THREAD

**Issue by patcon** [xdarklight/cm-update-server#3]
Here's the error:

https://gist.github.com/patcon/828ebdd0d09898e34ff4

I should also state that the zip file is not actually in place right now, and I'm assuming the server doesn't care about that yet (ie. it's just going to toss me a download url in the response, without checking)

Any insight is appreciated!

**Comment by xdarklight** [comment]
Can you tell me the sequelize version that you are using?

**Comment by patcon** [comment]
Sure. Here's a shrinkwrap I just generated: https://gist.github.com/patcon/50cd7ad4b2fa23641607

(I've added `sequelize-cli` as that was needed for migration. Haven't pushed the changes yet, as there's other little documentation gotchas I'm finding as I work through.)

**Comment by xdarklight** [comment]
I should learn those github hooks (as I didn't meant to close this).
Can you please try again with 4108180?

**Comment by patcon** [comment]
Nice! Seems to work now: https://gist.github.com/f2b27ecf1d3da7a8f481

not sure if `id` being `null` is something expected though..?

**Comment by xdarklight** [comment]
`id` isn't sent by the closed source server behind https://download.cyanogenmod.org/api as well - so yes: that's expected :)

**Comment by patcon** [comment]
Ah gotcha. Thanks @xdarklight!
