### ISSUE TITLE
npm update fails

### ISSUE THREAD

**Issue by imrasalghul** [xdarklight/cm-update-server#8]
When running npm update, this fails on my system. Tested on both CentOS and Ubuntu and failed on both:
test -d node_modules && ./node_modules/.bin/cake build || cake build

npm-debug log: http://pastebin.com/3BKJSvaY

**Comment by xdarklight** [comment]
according to the log it fails to install troll-opt:

```
457 error code ELIFECYCLE
458 error troll-opt@0.7.1 install: `test -d node_modules && ./node_modules/.bin/cake build || cake build`
458 error Exit status 1
459 error Failed at the troll-opt@0.7.1 install script 'test -d node_modules && ./node_modules/.bin/cake build || cake build'.
```

However, troll-opt installs fine for me.

Could you please show the output of `ls node_modules`

**Comment by imrasalghul** [comment]
![screen shot 2016-03-20 at 9 10 12 pm](https://cloud.githubusercontent.com/assets/2022965/13908762/2e0b79d2-eee0-11e5-8c96-d7af6df56036.png)

**Comment by xdarklight** [comment]
do you have "coffeescript" installed globally?
it's needed to build troll-opt.

I just tried `npm update` with a clean cm-update-server installation and it's working fine for me.
Could you also try deleting `/path/to/cm-update-server/node_modules` and run npm update again (keep backups in case..).

**Comment by ratmole** [comment]
i had the same issue and the problem is resolved by performing the following:
`$ npm update (on a clean cm-update-server installation)`
after the troll-opt@0.7.1 error:

```
$ cd node_modules/
$ git clone https://github.com/relistan/troll-opt.git
$ cd troll-opt/
$ cake build
$ rm -rf .git/
$ cd ../../
$ npm update
```

and then install undescore:
`$ npm install underscore`

now everything works

**Comment by xdarklight** [comment]
is this still reproducible?

**Comment by imrasalghul** [comment]
Nope, it's all working fine now! :+1:
