### ISSUE TITLE
Does not work with any node4 or 6 versions of nodejs.

### ISSUE THREAD

**Issue by imrasalghul** [xdarklight/cm-update-server#9]
Confirmed by installing nodejs-v4, and nodejs-v6, and then subsequently reinstalling nodejs 0.10. 

The conflict lies in troll-opt, which fails during npm-update.

Conflict log is here: https://gist.github.com/TheNameIsNigel/05bd8cc52133229472d118b234ad39d6

**Comment by xdarklight** [comment]
this seems to have been reported upstream: relistan/troll-opt#2
I wonder if I should be switching to https://github.com/yargs/yargs instead

**Comment by imrasalghul** [comment]
Probably since troll-opt is EOL per the dev

https://github.com/relistan/troll-opt/issues/2#issuecomment-167017329

**Comment by xdarklight** [comment]
the code is still mostly untested, but I started porting cm-update-server to yargs (in a separate feature-branch): dfe183f2ee14cdda1962945689d5e318893e89f0
If you want you can give that a go and report any bugs :).

**Comment by imrasalghul** [comment]
Been using it since you pushed the branch, and we've been running smoothly here. No bugs encountered at the present moment.

Tested on Nodejs v6.9.5.

**Comment by xdarklight** [comment]
thanks for reporting back.
I also did some tests and got the same result as you -> pushed that fix to master.
